### ISSUE TITLE
Unicode characters in strings need to be encoded

### ISSUE THREAD

**Issue by Fredyy90** [BaseMax/JsonParser#1]
Hi,

I just found your library and while skipping over the code i saw that you didn't implement correct encoding for unicode characters yet.

Please see this rfc for more information: https://tools.ietf.org/html/rfc8259#section-7

**Comment by BaseMax** [comment]
_Hello Frederick Behrends,_ @Fredyy90

Yes it was in my mind.
But was not included in the first version. (alpha, beta)
I would appreciate your request.
I added this. (https://github.com/BaseMax/JsonParser/releases/)

Note: Your name displayed in the code.
> This feature is requested by Frederick Behrends.

You can test it and notice to us. :+1: 

_Regards._
